version: 2.1

defaults: &defaults
      docker:
      - image: circleci/node:13.8.0               
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontendbuild]
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            # Your code here
            npm update
            npm run build
      - save_cache:
          paths: [frontend/mynode_modules]
          key: frontendbuild

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backendbuild]
      - run:
          name: Back-end build
          working_directory: ./backend
          command: |
              # Your code here
              npm update
              npm run build
      - save_cache:
          paths: [backend/mnode_modules]
          key: backendbuild
  

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend

