version: 2.1

defaults: &defaults
      docker:
      - image: circleci/node:13.8.0               
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontendbuild]
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            # Your code here
            npm update
            npm run build
      - save_cache:
          paths: [frontend/mynode_modules]
          key: frontendbuild

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backendbuild]
      - run:
          name: Back-end build
          working_directory: ./backend
          command: |
              # Your code here
              npm update
              npm run build
      - save_cache:
          paths: [backend/mnode_modules]
          key: backendbuild
  
  test-frontend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [frontendtest]
      - run:
          name: front-end test
          command: |
            cd frontend
            npm install
            npm install @babel/core @babel/preset-typescript @babel/preset-env
            npm run test
                
      - save_cache:
          paths: [frontend/node_modules]
          key: frontendtest
                
  test-backend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [backendtest]
      - run:
          
          name: Back-end test
          command: |
            cd backend
            npm install
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backendtest

    
  scan-frontend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [front-scan]
      commands: |
         cd frontend
         npm install
         npm run audit
      - save_cache:
          paths: [front/node_modules]
          key: front-scan

  scan-backend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [backend-scan]
      commands: |
         cd backend
         npm install
         npm run audit
      - save_cache:
          paths: [backend/node_modules]
          key: backend-scan


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
