version: 2.1
orbs:
  slack: circleci/slack@4.1

defaults: &defaults
      docker:
      - image: circleci/node:13.8.0    
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy backend stack
          command: |
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail
      - run:
          name: Destroy frontend stack
          command: |
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail
           
jobs:

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            # Your code here
            npm uninstall
            npm cache clean --force
            npm install
            npm run build
      - save_cache:
          paths: [frontend/mynode_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          working_directory: ./backend
          command: |
              # Your code here
              npm uninstall
              npm cache clean --force
              npm install
              npm run build
      - slack/notify:
          event: fail
          template: basic_fail_1     
      - save_cache:
          paths: [backend/mnode_modules]
          key: backend-build

  test-frontend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [frontend-test]
      - run:
          name: front-end test
          command: |
            cd frontend
            npm uninstall
            npm cache clean --force
            npm install
            npm install @babel/core @babel/preset-typescript @babel/preset-env
            npm run test  
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-test
                
  test-backend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [backend-test]
      - run:
          
          name: Back-end test
          command: |
            cd backend
            npm uninstall
            npm cache clean --force
            npm install
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backend-test



  scan-frontend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [mnfront-scan]
      - run: 
          name: front-end scan
          command: |
            cd frontend
            npm uninstall
            npm cache clean --force
            npm install
            npm audit fix --audit-level=critical --force
      - slack/notify:
          channel: C01SXTR5L4V
          event: fail
          template: basic_fail_1
      - save_cache:
          paths: [front/node_modules]
          key: mnfront-scan

  scan-backend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout

      - restore_cache:
          keys: [mnbackend-scan]
      - run: 
          name: Back-end scan
          command: |
            cd backend
            npm uninstall
            npm cache clean --force
            npm install
            npm audit fix --audit-level=critical --force
      - slack/notify:
          channel: C01SXTR5L4V
          event: fail
          template: basic_fail_1

      - save_cache:
          paths: [backend/node_modules]
          key: mnbackend-scan
      

  
  configure-infrastructure:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["db:88:54:02:a5:95:7c:f0:c4:71:43:09:ef:36:ec:b6"]
        - attach_workspace:
            at: ./.circleci/ansible
        - run:
            name: Install dependencies
            command: |
              yum -y install tar
              yum -y install gzip
              apk add --no-cache \
                  python3 \
                  py3-pip \
              && pip3 install --upgrade pip \
              && pip3 install \
                  awscli \
              && rm -rf /var/cache/apk/*
              apk add --update ansible
              
        - run:
            name: Configure server
            command: |
              ansible-playbook -i inventory .circleci/ansible/configure-server.yml

       
        - destroy-environment # Rollback on failure

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
      - add_ssh_keys:
            fingerprints: ["db:88:54:02:a5:95:7c:f0:c4:71:43:09:ef:36:ec:b6"]
      - run:
          name: Installing dependencies
          command: |
            yum install -y tar gzip curl
           
      
      - run:
          name: Ensure back-end infrastructure exists
          working_directory: ./.circleci/files
          command: |
            echo -e "[web]\n" >> ./.circleci/ansible/inventory.txt
            aws cloudformation deploy \
              --template-file backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
      
      - run:
          name: backend URL memstash
          command: |
            
            myIP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text)
            echo $myIP
            echo $myIP > ./.circleci/ansible/inventory.txt
            curl -H "Content-Type: text/plain" -H "token:  ${CIRCLE_WORKFLOW_ID:0:7}" --request PUT \ --data "$myIP:3030" https://api.memstash.io/values/myIP:3030
   
      
      
      - run:
      
          name: Ensure front-end infrastructure exist
          working_directory: ./.circleci/files
          command: |
            aws cloudformation deploy \
              --template-file frontend.yml \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: Add back-end ip to ansible inventory
          working_directory: ./.circleci/ansible
          command: |
           aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text >> .circleci/ansible/inventory.txt
            cat inventory.txt
            
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/ansible/inventory.txt

      - destroy-environment
      # Here's where you will add some code to rollback on failure    
          


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend

      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
          context: slack-secrets
      - scan-frontend:
          requires: [build-frontend]

      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [main]
 
      - configure-infrastructure:
          requires: [deploy-infrastructure]

      

