version: 2.1
orbs:
  slack: circleci/slack@4.1

defaults: &defaults
      docker:
      - image: circleci/node:13.8.0    
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy backend stack
          command: |
            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail
      - run:
          name: Destroy frontend stack
          command: |
            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail
           
jobs:

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            # Your code here
            npm uninstall
            npm cache clean --force
            npm install
            npm run build
      - save_cache:
          paths: [frontend/mynode_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          working_directory: ./backend
          command: |
              # Your code here
              npm uninstall
              npm cache clean --force
              npm install
              npm run build
      - slack/notify:
          event: fail
          template: basic_fail_1     
      - save_cache:
          paths: [backend/mnode_modules]
          key: backend-build

  test-frontend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [frontend-test]
      - run:
          name: front-end test
          command: |
            cd frontend
            npm uninstall
            npm cache clean --force
            npm install
            npm install @babel/core @babel/preset-typescript @babel/preset-env
            npm run test  
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-test
                
  test-backend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [backend-test]
      - run:
          
          name: Back-end test
          command: |
            cd backend
            npm uninstall
            npm cache clean --force
            npm install
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backend-test



  scan-frontend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout
      - restore_cache:
          keys: [mnfront-scan]
      - run: 
          name: front-end scan
          command: |
            cd frontend
            npm uninstall
            npm cache clean --force
            npm install
            npm audit fix --audit-level=critical --force
      - slack/notify:
          channel: C01SXTR5L4V
          event: fail
          template: basic_fail_1
      - save_cache:
          paths: [front/node_modules]
          key: mnfront-scan

  scan-backend:
    <<: *defaults
    steps:
      # Checkout code from git
      # Restore from cache
      # Your job code here
      - checkout

      - restore_cache:
          keys: [mnbackend-scan]
      - run: 
          name: Back-end scan
          command: |
            cd backend
            npm uninstall
            npm cache clean --force
            npm install
            npm audit fix --audit-level=critical --force
      - slack/notify:
          channel: C01SXTR5L4V
          event: fail
          template: basic_fail_1

      - save_cache:
          paths: [backend/node_modules]
          key: mnbackend-scan
      



  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
     
      - run:
          name: Installing dependencies
          command: |
            yum install -y tar gzip curl
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udacity Name=Backend \
              --stack-name backend-"${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
            BACKEND_IP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text)
            echo $BACKEND_IP
            curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request PUT \
              --data "$BACKEND_IP" https://api.memstash.io/values/BACKEND_IP
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udacity Name=Frontend \
              --stack-name frontend-"${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            echo "[web]" > .circleci/ansible/inventory.txt
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - destroy-environment


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend

      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
          context: slack-secrets
      - scan-frontend:
          requires: [build-frontend]

      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [main]
 

      

